### ISSUE TITLE
In Examples, Ctrl+C Errors on Exit with Simulated Robot

### ISSUE THREAD

**Issue by rethink-imcmahon** [RethinkRobotics/baxter_examples#48]
A crossover issue from https://github.com/RethinkRobotics/baxter_simulator/issues/58. The gist:
When running `baxter_examples joint_velocity_wobbler.py` on the `baxter_simulator` robot, and Ctrl+C is asserted by the user, various errors can be produced by `rospy` on exit:
__A Timer Error:__
```
~/ros_ws$ ./baxter.sh sim
~/ros_ws$ rosrun baxter_examples joint_velocity_wobbler.py
[INFO] [WallTime: 1441031503.775147] [128.230000] Robot Enabled
[INFO] [WallTime: 1441031549.388135] [173.643000] Robot Disabled
File "/home/baxter/ros_ws/src/baxter_examples/scripts/joint_velocity_wobbler.py", line 158, in
File "/home/baxter/ros_ws/src/baxter_examples/scripts/joint_velocity_wobbler.py", line 153, in
File "/home/baxter/ros_ws/src/baxter_examples/scripts/joint_velocity_wobbler.py", line 134, in
File "/opt/ros/indigo/lib/python2.7/dist­packages/rospy/timer.py", line 99, in sleep
File "/opt/ros/indigo/lib/python2.7/dist­packages/rospy/timer.py", line 157, in sleep
raise rospy.exceptions.ROSInterruptException("ROS shutdown request")
rospy.exceptions.ROSInterruptException: ROS shutdown request
```
__A baxter_interface Limb Error:__
```
$ rosrun baxter_examples joint_velocity_wobbler.py 
Initializing node... 
Getting robot state... 
Enabling robot... 
[INFO] [WallTime: 1441731848.427393] [7726.313000] Robot Enabled
Moving to neutral pose...
Left Moving to neutral pose complete...
Right Moving to neutral pose complete...
Wobbling. Press Ctrl-C to stop...
^C
Exiting example...
Moving to neutral pose...
Left Moving to neutral pose complete...
Right Moving to neutral pose complete...
Disabling robot...
[INFO] [WallTime: 1441731868.003786] [7745.839000] Robot Disabled
Finished shutdown check...
Traceback (most recent call last):
  File "/data/users/imcmahon/dev/mrsp_ws/src/baxter_examples/scripts/joint_velocity_wobbler.py", line 164, in <module>
    main()
  File "/data/users/imcmahon/dev/mrsp_ws/src/baxter_examples/scripts/joint_velocity_wobbler.py", line 159, in main
    wobbler.wobble()
  File "/data/users/imcmahon/dev/mrsp_ws/src/baxter_examples/scripts/joint_velocity_wobbler.py", line 136, in wobble
    self._right_arm.set_joint_velocities(cmd)
  File "/data/users/imcmahon/dev/mrsp_ws/src/baxter_interface/src/baxter_interface/limb.py", line 367, in set_joint_velocities
    self._pub_joint_cmd.publish(self._command_msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 819, in publish
    self.impl.publish(data)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 999, in publish
    b.tell()
AttributeError: 'NoneType' object has no attribute 'tell'
```
This is likely a `rospy` `simulated_time` timer issue, since the `joint_velocity_wobbler` script does not error like this on the real robot, but it is desirable to find a fix that would prevent this issue entirely.

**Comment by rethink-imcmahon** [comment]
Either this should get fixed in all [13 of our examples with on_shutdown behavior](https://github.com/RethinkRobotics/baxter_examples/search?p=1&q=%22rospy.on_shutdown%22&type=Code&utf8=%E2%9C%93) or the root cause needs to be sussed out in `ros_comm/rospy` in simulation

**Comment by rethink-imcmahon** [comment]
Appears there was an underlying `rospy` issue in `ros_comm`:
https://github.com/ros/ros_comm/commit/2e84880a6f494e32bc016d414990e6d3f17b8de6
https://github.com/ros/ros_comm/pull/690

@stonier thanks for fixing this!
